name: 新功能提议
description: 提出一个新的产品功能建议
title: "[新功能] - "
labels: ["新功能"]
type: feature_request
body:
  - type: markdown
    attributes:
      value: |
        感谢你的功能建议！请尽可能详细地描述你的想法，以便我们更好地理解和评估它。

  - type: textarea
    id: feature-description
    attributes:
      label: 功能描述
      description: 请简单描述想要的功能是什么，以及它的主要用途场景。
      placeholder: 这里描述你的功能提议
      value: ""
    validation
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 预期效果
      description: 你期望这个功能如何工作？请尽量详细描述。
      placeholder: 例如：“当用户点击某个按钮时，系统应该……”
      value: ""
    validations:
      required: true

  - type: checkboxes
    id: target-users
    attributes:
      label: 目标用户
      description: 这个功能主要面向哪些用户群体？如果没有适用选项，请选择“其他”并填写下方输入框。
      options:
        - label: 个体用户
        - label: 企业用户
        - label: 其他

    - type: input
      id: target-users-other
      attributes:
        label: 其他用户群体
        description: 如果上方选项不适用，请在此处填写具体用户群体。
        placeholder: 请输入其他适用用户群体
        value: ""

  - type: textarea
    id: alternatives
    attributes:
      label: 其他可行方案
      description: 是否有其他方法可以达到相同的目标？请简要描述。
      placeholder: 例如：“我们可以通过调整现有功能来实现类似效果……”
      value: ""
  
  - type: textarea
    id: additional-context
    attributes:
      label: 补充说明
      description: 你还有什么补充说明吗？可以附加相关文档、截图或参考链接。
      placeholder: 这里可以填写任何额外信息
      value: ""