name: 其他情况
description: 如果以上模版不符合需求，请选择【其他情况】
title: "[其他] - "
labels: []
type: other_request
body:
  - type: markdown
    attributes:
      value: |
        感谢你的建议！请尽可能详细地描述你的想法，以便我们更好地理解和评估它。

  - type: textarea
    id: feature-description
    attributes:
      label: 描述
      description: 请描述当前情况。
      placeholder: 这里描述情况
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 其他可行方案
      description: 是否有其他方法可以达到相同的目标？请简要描述。
      placeholder: 例如：“我们可以通过调整现有功能来实现类似效果……”
  
  - type: textarea
    id: additional-context
    attributes:
      label: 补充说明
      description: 你还有什么补充说明吗？可以附加相关文档、截图或参考链接。
      placeholder: 这里可以填写任何额外信息